# Site settings
title: Dan Morrison
email: dan@danm.it
description: >
  You can follow me on <a class='github' href='https://github.com/danmorrison'>GitHub</a>,
  <a class='linkedin' href='http://linkedin.com/in/danjmorrison'>LinkedIn</a>,
  <a class='applemusic' href='https://itunes.apple.com/profile/danmorrison'>Apple Music</a>,
  <a class='runkeeper' href='http://runkeeper.com/user/danmorrison'>Runkeeper</a>,
  <a class='babbel' href='https://babbel.com/profiles/2952c1cdbb9ae0d267bf1df21d92d5ba'>Babbel</a> and
  <a class='imdb' href='http://imdb.com/user/ur25415537'>IMDb</a>
  and my daughter on <a class='instagram' href='https://instagram.com/gwengracelee'>Instagram</a>.
baseurl: ""
url: "http://danm.it" # the base hostname & protocol for your site
github_username: danmorrison

# Build settings
markdown: kramdown
permalink: none
timezone: Australia/Melbourne

