# Site settings
title: Dan Morrison
email: dan@danm.it
description: >
  You can follow me on <a class='github' href='https://github.com/danmorrison'>GitHub</a>,
  <a class='linkedin' href='http://linkedin.com/in/danjmorrison'>LinkedIn</a>,
  <a class='applemusic' href='https://itunes.apple.com/profile/danmorrison'>Apple Music</a> and
  <a class='letterboxd' href='https://letterboxd.com/danielmorrison'>Letterboxd</a>
  and my daughter on <a class='instagram' href='https://instagram.com/gwengracelee'>Instagram</a>.
baseurl: ""
url: "http://danm.it" # the base hostname & protocol for your site
github_username: danmorrison

# Build settings
markdown: kramdown
permalink: none
timezone: Australia/Melbourne

