# Site settings
title: Daniel Morrison
email: dan@danm.it
description: >
  You can follow my work on <a class='linkedin' href='http://linkedin.com/in/danjmorrison'>LinkedIn</a>
  and <a class='github' href='https://github.com/danmorrison'>GitHub</a>,
  my playlists on <a class='applemusic' href='https://itunes.apple.com/profile/danmorrison'>Apple Music</a>,
  my film reviews on <a class='letterboxd' href='https://letterboxd.com/danielmorrison'>Letterboxd</a>
  and my photos on <a class='instagram' href='https://instagram.com/daniel.j.morrison'>Instagram</a>.
  
baseurl: ""
url: "http://danm.it" # the base hostname & protocol for your site
github_username: danmorrison

# Build settings
markdown: kramdown
permalink: /:categories/:title
timezone: Australia/Melbourne


